# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: landmark_detection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'landmark_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18landmark_detection.proto\x12\x12landmark_detection\"4\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x10\n\x08image_id\x18\x02 \x01(\t\"_\n\x10LandmarkResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08image_id\x18\x02 \x01(\t\x12\x11\n\tredis_key\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2n\n\x11LandmarkDetection\x12Y\n\x0f\x44\x65tectLandmarks\x12 .landmark_detection.ImageRequest\x1a$.landmark_detection.LandmarkResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'landmark_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=48
  _globals['_IMAGEREQUEST']._serialized_end=100
  _globals['_LANDMARKRESPONSE']._serialized_start=102
  _globals['_LANDMARKRESPONSE']._serialized_end=197
  _globals['_LANDMARKDETECTION']._serialized_start=199
  _globals['_LANDMARKDETECTION']._serialized_end=309
# @@protoc_insertion_point(module_scope)
